plugins {
	id("multiloader-common")
}

ext.configureRuns = { runs ->
	def mixinsJar = configurations.named("runtimeClasspath").map {
		it.resolvedConfiguration.resolvedArtifacts.find {
			it.moduleVersion.id.group == "net.fabricmc" && it.moduleVersion.id.name == "sponge-mixin"
		}.getFile()
	}
	runs.configureEach { config ->
		config.generateRunConfig = config.preferGradleTask = true
		config.systemProperties.put("mixin.debug.export", "true")
		config.jvmArguments.add(mixinsJar.map { "-javaagent:${it.absolutePath}" })
	}
}

configurations {
	def commonJavaDep = dependencyScope("commonJavaDep")
	resolvable("commonJava") {
		extendsFrom(commonJavaDep)
	}

	def commonResourcesDep = dependencyScope("commonResourcesDep")
	resolvable("commonResources") {
		extendsFrom(commonResourcesDep)
	}
}

dependencies {
	compileOnly(project(":${rootProject.name}-common")) {
		attributes { attribute(Attribute.of("io.github.mcgradleconventions.loader", String), "common") }
	}

	commonJavaDep(project(path: ":${rootProject.name}-common", configuration: "commonJava"))
	commonResourcesDep(project(path: ":${rootProject.name}-common", configuration: "commonResources"))

	annotationProcessor(compileOnly("com.google.auto.service:auto-service:1.1.1"))
}

tasks.named("compileJava", JavaCompile).configure {
	dependsOn(configurations.commonJava)
	source(configurations.commonJava)
}
tasks.named("processResources", ProcessResources).configure {
	dependsOn(configurations.commonResources)
	from(configurations.commonResources)
}
tasks.named("sourcesJar", Jar).configure {
	dependsOn(configurations.commonJava, configurations.commonResources)
	from(configurations.commonJava, configurations.commonResources)
}
