# NeoForge Properties
neoforge_version = 26.1.2.100
# NeoForge Dependencies
launchpad_version = 1.9.2+26.1.2
forgified_fabric_api_version = 0.155.2+26.1.2+3.5.5
# Chenille
mr_requirements = launchpad; forgified-fabric-api; strawberrylib
cf_requirements = launchpad; forgified-fabric-api; strawberrylib
